### ISSUE TITLE
Feature request: sensor allowlist & labeling with human readable names

### ISSUE THREAD

**Issue by stelas** [joneskoo/ruuvi-prometheus#2]
Great project! :+1:
I'm using ruuvi-prometheus in combination with Grafana on my home server as indoor weather station.

Is it possible to add a whitelist of monitored beacons and give them alias names in the metrics export?
Key-value file example:
```
aa:bb:cc:dd:ee:ff = Fridge
aa:bb:cc:xx:yy:zz = Outdoor
```

**Comment by joneskoo** [comment]
Thanks.

I use ruuvi-prometheus on a stateless Raspberry Pi and I don't want it to have to care about where the sensors are or what to do with them. The less configuration the better.

I have physically labeled my tags with sequential numbers 1-9 on sticker. Here's what I use in `prometheus.yml` to relabel human readable names for Grafana. Arguably it's verbose, but straightforward, does the job and I don't change it often. Alternatively it's possible to provide labels from another exporter and add them in the query. I believe this is explained in Prometheus docs.

Discarding values should be possible similarly on prometheus-side. I doubt you have too many sensors in range that it would cause too many data points to store?

Adding a simplified example of this to the README would be welcome, if you wish to contribute it.

```yaml
  - job_name: 'ruuvi-prometheus'
    static_configs:
      - targets: ['ruuvi-prometheus.m7.yx.fi:9521']
    metric_relabel_configs:
      - source_labels: ['device']
        regex: 'e7:37:3b:37:d9:74'
        target_label: 'id'
        replacement: '2'
      - source_labels: ['id']
        regex: '2'
        target_label: 'name'
        replacement: 'autotalli'
      # ...
      - source_labels: ['id']
        regex: '2|3|5|6|7|9'
        target_label: 'location'
        replacement: 'sisällä'
      - source_labels: ['device']
        regex: 'ca:7a:36:11:a7:16'
        target_label: 'id'
        replacement: '1'
      - source_labels: ['id']
        regex: '1'
        target_label: 'name'
        replacement: 'välikatto'
      - source_labels: ['device']
        regex: 'ea:11:ea:d7:ca:91'
        target_label: 'id'
        replacement: '4'
      - source_labels: ['id']
        regex: '4'
        target_label: 'name'
        replacement: 'vaja'
      - source_labels: ['id']
        regex: '1|4'
        target_label: 'location'
        replacement: 'ulkona'
```
